[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "b_chromatic_colouring_mendoza95"
version = "0.0.1"
authors = [
  { name="Fabricio Mendoza Granada", email="fabromendoza95@gmail.com" },
]
description = "A small package containing  linear time algorithm for finding the b-chromatic number of a tree and a cubic graph, and an IP model for finding the total b-chromatic number of a graph."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/mendoza95/b_chromatic_colouring"
Issues = "https://github.com/mendoza95/b_chromatic_colouring/issues"